### ISSUE TITLE
Physical parameterizations: inconsistencies between speedy.f90 and the Speedy Documentation

### ISSUE THREAD

**Issue by white-alistair** [SpeedyWeather/SpeedyWeather.jl#126]
The most up-to-date documentation of the original Speedy is [here](http://users.ictp.it/~kucharsk/speedy_description/km_ver41_appendixA.pdf).

With respect to the physical parameterizations, a number of apparent inconsistencies exist between the documentation and the implementation in [speedy.f90](https://github.com/samhatfield/speedy.f90).

We will record them in this issue.

**Comment by white-alistair** [comment]
## 1. Convection (WIP)
![Screenshot from 2022-08-22 13-44-41](https://user-images.githubusercontent.com/59571934/186108360-e25ca3c0-03b9-4481-ae1b-1b499e5a08f1.png)
### 1.1. Levels where convection may occur
The docs say: 
> A tropospheric level exists (with $1 < k < N − 1$)...

This is already inconsistent since we know the top two levels (k=1, 2) represent the stratosphere. 

The [loop](https://github.com/samhatfield/speedy.f90/blob/0ebfdbfcd62efd46dd1802284908645be4b230be/source/convection.f90#L211) in speedy.f90 uses the range `k = kx-3, 3, -1`, which excludes the stratosphere and also the layer directly above the PBL, i.e. k = N-2.

**Clarification needed**: I think the range used in speedy.f90 is probably fine, but I would like to understand why exactly the layer directly above the PBL is excluded.

### 1.2. Gradient of moist static energy between lower and upper troposphere
An initial reading of the docs might suggest that convection is activated where both eqs. 6 and 7 are satisfied simultaneously, _for the same value of k_. However, the [implementation](https://github.com/samhatfield/speedy.f90/blob/0ebfdbfcd62efd46dd1802284908645be4b230be/source/convection.f90#L170) in speedy.f90 activates convection where both equations are satisfied somewhere within a given column, albeit not necessarily for the same value of k.

**Clarification needed**: What is the correct logic?

Eq. 7, as written, has saturation moist static energy (MSS) on both sides of the inequality, but the [comparison](https://github.com/samhatfield/speedy.f90/blob/0ebfdbfcd62efd46dd1802284908645be4b230be/source/convection.f90#L222) in speedy.f90 has moist static energy (MSE) on the left-hand side.

**Clarification needed**: Which version of the equation is correct?

**Comment by milankl** [comment]
@white-alistair Did you make any conclusions about these inconsistencies? I'm currently restructuring your work and hitting the same issues.

**Comment by milankl** [comment]
@samhatfield do you know whether any of these inconsistencies could have been introduced because the Fortran77 you started from is not what Franco Molteni based the documentation on? Or did anyone else play around with the code after the documentation was written?

**Comment by white-alistair** [comment]
> @white-alistair Did you make any conclusions about these inconsistencies? I'm currently restructuring your work and hitting the same issues.

Unfortunately not. Happy to help wherever I can though.

**Comment by milankl** [comment]
I cannot find any documentation about the pressure threshold for convection that's in the F90 code, tempted to skip it, because I don't understand physically why you (effectively) would disable convection above mountains

https://github.com/samhatfield/speedy.f90/blob/0ebfdbfcd62efd46dd1802284908645be4b230be/source/convection.f90#L199

**Comment by milankl** [comment]
For a typical surface pressure field this p/p0 > 0.8 condition would disable convection always in Tibet, Greenland, Antarctica etc (non-purple patches in the bottom)

![image](https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/d8b41ebd-7354-41da-b125-abcf605dd117)

**Comment by samhatfield** [comment]
I would guess the documentation is incorrect. Example: the wording `if a tropospheric level exists (with 1 < k < N − 1)` is identical in the two versions of the documentation describing the [8-level version](https://users.ictp.it/~kucharsk/speedy_description/km_ver41_appendixA.pdf) and the [5-level version](https://users.ictp.it/~kucharsk/speedy_description/molteni2002_appendixA.pdf). I guess the 5-level version has a single tropospheric level so it is correct there, and the docs weren't updated when another tropo level was added later (as you also spotted @white-alistair).

Perhaps the other changes weren't reflected in the docs?

**Comment by milankl** [comment]
Do you mean tropopause/stratosphere level? Or the planetary boundary layer? Because 8-level Fortran SPEEDY assumes the top 2 levels to be tropopause/stratosphere and the bottom one to be the boundary layer no?

**Comment by milankl** [comment]
Btw, I'm trying to generalise this to each some sigma level above/below which levels are considered to be tropopause/stratopshere or boundary layer respectively.

**Comment by milankl** [comment]
At the moment they are
```julia
julia> atmopshere = EarthAtmosphere()
EarthAtmosphere
├ mol_mass_dry_air::Float64 = 28.9649
...
├ σ_tropopause::Float64 = 0.2
├ σ_boundary_layer::Float64 = 0.95
...

**Comment by samhatfield** [comment]
> Do you mean tropopause/stratosphere level? Or the planetary boundary layer? Because 8-level Fortran SPEEDY assumes the top 2 levels to be tropopause/stratosphere and the bottom one to be the boundary layer no?

Yes you're right - replace "troposphere" with "stratosphere" in my comment.

**Comment by milankl** [comment]
Closing this as we now have a Betts-Miller convection scheme, which is more general (it doesn't have anything Fortran SPEEDY specific hardcoded, such as number of whatever layers) and requires less tuning (only two parameters). See #442 and #467
