### ISSUE TITLE
Move to SpeedyWeather orga

### ISSUE THREAD

**Issue by milankl** [SpeedyWeather/SpeedyWeather.jl#182]
I've just created [github.com/SpeedyWeather](https://github.com/SpeedyWeather) but before transferring the ownership of this repository to the orga (which is in the "danger zone") I wanted to make sure that this is the right way to go and that everyone agrees.

@maximilian-gelbrecht @dmey

**Comment by maximilian-gelbrecht** [comment]
I like having an orga for this. There's also nothing that could go wrong with this, right?

**Comment by milankl** [comment]
The docs aren't working, anyone an idea where they went?
