### ISSUE TITLE
Liniting

### ISSUE THREAD

**Issue by dmey** [SpeedyWeather/SpeedyWeather.jl#220]
Linting is somewhat clunky in VSCode with a lot of warning etc and I wonder whether this is because of the current packages or something else? @milankl are you experiencing the same?

**Comment by milankl** [comment]
I admire your efforts but honestly don't mind that much. We are all well on the "readable code" part of the spectrum, so whether someone writes `2^i*3` or `2^i * 3`, and `f(a,b)` or `f(a, b)` I honestly don't care. And I don't even mind if it's not consistent. I believe for good code practice there's other things that are way more important that cannot be automated, like naming, comments, rather several small functions than one big one, etc etc. I feel this is an "issue" in software development that's easily over-engineered. If we were start writing unindented highschool code maybe, but we're not doing that anyway.

I don't know what the Linting check does, but preventing a pull request from being merged sounds rather harsh. Automatically changing the style upon merging sounds okay to me though.

**Comment by white-alistair** [comment]
For what it's worth, I am a huge fan of using an auto-formatter to achieve a consistent code style across a project, even more so a big project like this one. It is the easiest of easy wins. Amongst other things, it makes the project feel clean and it takes the burden of formatting off the developer.

Personally I wouldn't fail the CI though.

**Comment by white-alistair** [comment]
@dmey I haven't had any issues with formatting in VSCode. Are you using the latest Julia VSCode plugin? What kind of warnings do you get?

**Comment by milankl** [comment]
If anyone wants to pick this up, https://github.com/domluna/JuliaFormatter.jl seems to offer what this issue proposes and can apply a certain format to all files in `src` for example. However, this does not seem to be an actual issue so I'll close it, but feel free to repoen
