### ISSUE TITLE
Outsourcing packages

### ISSUE THREAD

**Issue by milankl** [SpeedyWeather/SpeedyWeather.jl#231]
Just a quick issue thread on which packages could be outsourced and made independent of SpeedyWeather.jl such that eventually SpeedyWeather.jl just imports them:

- **RingGrids.jl** everything in `/Grids` which defines `AbstractGrid`, all its subtypes (FullGaussianGrid, ..., Octahedral..., HEALPixGrid), and the interpolation engine. I propose RingGrids.jl because all of these grids have to be ring-based.
- **LowerTriangularMatrices.jl** implements the lower triangular matrices used for the spherical harmonic coefficients. This is pretty stand-alone, and just a more memory efficient matrix type.
- **SpeedyTransform.jl**, the spectral transform library and depends on the previous too to transform between grid and spectral space. This package would definitely be much closer to SpeedyWeather.jl as I realised that I needed to keep tweaking things for interoperability with the rest of the dynamical core over the last months although the transforms conceptually didn't change.

I believe RingGrids.jl and LowerTriangularMatrices.jl are basically ready to be outsourced, but I'm hesitating still with SpeedyTransform.jl as its functionality is much more entangled with the dynamical core. All of them could obviously just go into the SpeedyWeather orga.

**Comment by maximilian-gelbrecht** [comment]
I agree on outsourcing RingGrids.jl and LowerTriangularMatrices.jl and I also agree about your concern regarding SpeedyTransform.jl. I think such a package should also include all the routines to take derivatives. And all of those especially are - as you stated - right now very much tied to what is needed for the dynamical core. It would be cool to have SpeedyTransform.jl as a separate package on the hand, as this could enable other people to build very different models with it with more ease. But maybe this is something for later, when we are a bit bored ;)

**Comment by milankl** [comment]
We should probably, as a first step, define these as modules and make them subpackages within the same repository under `SpeedyWeather/lib/RingGrids`, `SpeedyWeather/lib/LowerTriangularMatrix.jl` etc. KernelAbstractions.jl or Dagger.jl do this too.

**Comment by milankl** [comment]
@kburns I guess you would have an interest to make **SpeedyTransform.jl** eventually a standalone package and not just a subpackage?

**Comment by kburns** [comment]
I'm not sure, many people probably will be using their own data structures and might prefer interacting with the more foundational transform libraries like FFTW and AssociatedLegendreTransforms. As you're saying, things higher level than that tend to be more coupled to each particular solver, etc.
