### ISSUE TITLE
Unable to open output files using NCDatasets.jl

### ISSUE THREAD

**Issue by natgeo-wong** [SpeedyWeather/SpeedyWeather.jl#236]
Hi!  I am getting a HDF error when I try to open the file using NCDatasets.jl

```
julia> using NCDatasets

julia> ds = NCDataset("output.nc")
ERROR: NetCDF error: Opening path output.nc: NetCDF: HDF error (NetCDF error code: -101)
Stacktrace:
 [1] nc_open(path::String, mode::UInt16)
   @ NCDatasets ~/.julia/packages/NCDatasets/gTGnf/src/netcdf_c.jl:274
 [2] NCDataset(filename::String, mode::String; format::Symbol, share::Bool, diskless::Bool, persist::Bool, memory::Nothing, attrib::Vector{Any})
   @ NCDatasets ~/.julia/packages/NCDatasets/gTGnf/src/dataset.jl:203
 [3] NCDataset (repeats 2 times)
   @ ~/.julia/packages/NCDatasets/gTGnf/src/dataset.jl:163 [inlined]
 [4] top-level scope
   @ REPL[2]:1
```

**Comment by milankl** [comment]
I believe this is because you use an apple arm chip. There has been issues with netcdf libraries and those in the past. @samhatfield could you check with your macbook whether you can reproduce this error and both post your NetCDF/NCDatasets versions?

**Comment by natgeo-wong** [comment]
I will also have a look at output.jl and see if I can write up an NCDatasets.jl version.

**Comment by milankl** [comment]
That would be fantastic! I thought about the transition for a while, and I'm happy to support this. `src/output.jl` should be the only file that needs actually reworking, otherwise we have `src/SpeedyWeather.jl` where NCDatasets.jl needs to be loaded and there are tests in `test/netcdf_output.jl` that need minor tweaks.

**Comment by samhatfield** [comment]
I can't reproduce the error on my M1 Macbook Pro:

```
julia> using SpeedyWeather
julia> run_speedy(n_days=30, trunc=63, Grid=OctahedralGaussianGrid, output=true)
julia> using NCDatasets
julia> ds = NCDataset("output.nc")
NCDataset: output.nc
Group: /

Dimensions
   time = 123
   lat = 128
   lev = 1
   lon = 256

Variables
  time   (123)
    Datatype:    Int32
    Dimensions:  time
    Attributes:
     units                = hours since 2000-01-01 00:00:0.0
     long_name            = time

  vor   (256 × 128 × 1 × 123)
    Datatype:    Float64
    Dimensions:  lon × lat × lev × time
    Attributes:
     units                = 1/s
     missing_value        = NaN
     long_name            = relative vorticity
     _FillValue           = NaN

  lat   (128)
    Datatype:    Float64
    Dimensions:  lat
    Attributes:
     units                = degrees_north
     long_name            = latitude

  lev   (1)
    Datatype:    Int32
    Dimensions:  lev
    Attributes:
     units                = 1
     long_name            = vertical model levels

  lon   (256)
    Datatype:    Float64
    Dimensions:  lon
    Attributes:
     units                = degrees_east
     long_name            = longitude
```

This is with 
- NCDatasets v0.12.12
- NetCDF v0.11.4
- SpeedyWeather v0.4.0

@natgeo-wong could you post your versions too?

**Comment by natgeo-wong** [comment]
Sorry, was away for the weekend and will get to this tomorrow!

**Comment by milankl** [comment]
Has this problem been resolved?

**Comment by natgeo-wong** [comment]
oooops sorry @milankl I came down with covid, so I've been kind of iffy recently. gimme a bit.

**Comment by natgeo-wong** [comment]
Hi everyone, my versions are as follows:

NCDatasets v0.12.12
NetCDF v0.11.7
SpeedyWeather v0.4.0#main

But it also appears that I have ... managed to get it to work now??????

I recently reinstalled everything again and it appears to work now so ... I guess this issue is closed? 😅

**Comment by samhatfield** [comment]
Hmmm! Odd. Well this is a happy outcome I guess?

**Comment by milankl** [comment]
Wonderful!
