### ISSUE TITLE
Cannot run example on non-GPU system

### ISSUE THREAD

**Issue by hearnsj** [SpeedyWeather/SpeedyWeather.jl#282]
julia> run_speedy(ShallowWater, n_days=30, trunc=63, Grid=OctahedralGaussianGrid, output=true)
ERROR: UndefVarError: ShallowWater not defined
Stacktrace:
 [1] top-level scope
   @ REPL[18]:1
 [2] top-level scope
   @ C:\Users\John_Hearns\.julia\packages\CUDA\BbliS\src\initialization.jl:52

I must be doing something wrong.  the first example fails.
This is Windows 11 / Julia 1.8.5 / no GPU

**Comment by milankl** [comment]
Sorry, the example is from #main, I'm working on the release but there's still a few issues to address!

**Comment by milankl** [comment]
I give this issue the documentation label as currently the readme is ahead of the last release, this issue should be closed when the next release is out

**Comment by milankl** [comment]
closing this with v0.5 released
