### ISSUE TITLE
Missing (-1)^{n+1} factor from hyperdiffusion term

### ISSUE THREAD

**Issue by navidcy** [SpeedyWeather/SpeedyWeather.jl#286]
Hyper diffusion term should be 

$$
(-1)^{n+1}\nabla^{2n}
$$

**Comment by milankl** [comment]
Just checked the operators with varying powers and they look good

![image](https://user-images.githubusercontent.com/25530332/230427915-e6f520cd-7425-4fb5-8f5b-3d1e18e56401.png)

I stumbled across this for the dynamics as we don't do any $(-1)^{n+1}$ business in spectral space, so I was confused for why that is, whereas you obviously have to do that with grid-point based operators.

**Comment by milankl** [comment]
Quite cool to see the impact: $\nabla^2$ very diffusive in the top, kills all the turbulence, only orography signal remains to $-\nabla^8$ at the bottom

![image](https://user-images.githubusercontent.com/25530332/230438315-4c311e57-efc6-4617-ba6a-9a8987ed0f96.png)

**Comment by navidcy** [comment]
> Just checked the operators with varying powers and they look good
> 
> ![image](https://user-images.githubusercontent.com/25530332/230427915-e6f520cd-7425-4fb5-8f5b-3d1e18e56401.png)
> 
> (ℓmax shoud be ℓ, my bad, but ℓmax=31 here, that's why they all coincide at this point)
> 
> I stumbled across this for the dynamics as we don't do any (−1)n+1 business in spectral space, so I was confused for why that is, whereas you obviously have to do that with grid-point based operators.
> 
> Update: Okay, it is because the eigenvalues of the laplace operator ∇2 in spherical harmonics are −ℓ(ℓ+1), so the eigenvalues of ∇2n are actually (−1)n(ℓ(ℓ+1))n. However, we normalise the ∇2n by the largest eigenvalue (such that the sign drops out too) and then consider the (normalised) diffusion coefficent as an (inverse) time scale ν∗ [1/s] (which is always positive) so we have in total
> 
> (−1)n+1ν∇2n=ν∗(ℓ(ℓ+1)ℓmax(ℓmax+1))n
> 
> Where on the left the (−1)n+1 compensates for the alternating (anti)dissipative nature of ∇2n, to always yield something dissipative. On the right the sign drops out because we normalise by the largest eigenvalue anyway and therefore retain the dissipative nature (and the sign in the figure above). Does that make sense? I'll try to update the docs to better explain that. Thanks for pointing this out.

In spectral space the minus sign of the eigenvalues of the Laplacian cancels out with the $(-1)^{n+1}$. E.g., in rectilinear coordinates, $\nabla^2 \to - k^2$ and thus

$$
(-1)^{n+1} \nabla^{2n} \to (-1)^{n+1} (- k^2)^n = - k^{2n}
$$

**Comment by milankl** [comment]
That's what I said, no?

**Comment by navidcy** [comment]
Yes, but it was before coffee for me so I got a bit confused with eigenvalue normalizing and thought I'd clarify. :)
