### ISSUE TITLE
Precompilation warnings?

### ISSUE THREAD

**Issue by navidcy** [SpeedyWeather/SpeedyWeather.jl#296]
Why all these warnings? Also where are they coming from? The warning mentions, e.g., `in module SpeedyWeather at util.jl:504` but where is this `util.jl` file?

```Julia
[ Info: Precompiling SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9]
WARNING: Method definition (::Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup})() in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/default_parameters.jl:345.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.Parameters{Model} where Model<:SpeedyWeather.ModelSetup}) in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/default_parameters.jl:345.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{SpeedyWeather.ColumnVariables{NF} where NF<:AbstractFloat})() in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/physics/define_column.jl:111.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.ColumnVariables{NF} where NF<:AbstractFloat}) in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/physics/define_column.jl:111.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{SpeedyWeather.LinearDrag{NF} where NF<:Real})() in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/physics/parameter_structs.jl:72.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.LinearDrag{NF} where NF<:Real}) in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/physics/parameter_structs.jl:72.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{SpeedyWeather.HeldSuarez{NF} where NF<:Real})() in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/physics/parameter_structs.jl:90.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition Type##kw(Any, Type{SpeedyWeather.HeldSuarez{NF} where NF<:Real}) in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/physics/parameter_structs.jl:90.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition (::Type{SpeedyWeather.Output{NF} where NF<:Union{Float32, Float64}})() in module SpeedyWeather at util.jl:504 overwritten at /Users/navid/Research/SpeedyWeather.jl/src/output/output.jl:43.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition speedstring(Any) in module ProgressMeter at /Users/navid/.julia/packages/ProgressMeter/sN2xr/src/ProgressMeter.jl:683 overwritten in module SpeedyWeather at /Users/navid/Research/SpeedyWeather.jl/src/output/pretty_printing.jl:29.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by navidcy** [comment]
Hm... This might be "type piracy"?

https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/1409af8ac50c3e33ac8a285dfef696966dcc6881/src/output/pretty_printing.jl#L29

**Comment by navidcy** [comment]
Also where is the `Parameters` dep used? (I'm wondering if there are name conflicts with the `SpeedyWeather.Parameters`?

**Comment by milankl** [comment]
We use from Parameters.jl only the @unpack, that’s why only that is imported. We could replace them with the (;fieldname,…) = somestruct notation and in fact we already do in dynamics/implicit.jl because @unpack is incompatible with @floop. I like @unpack because it’s more explicit than (; … ) = … but would be happy to remove the Parameters.jl dependency in the long run

**Comment by milankl** [comment]
> Hm... This might be "type piracy"?
> 
Yes, I didn’t want to go down the route of implementing the speed estimate properly in ProgressMeter.jl and instead went for the easy way to just locally redefine their function so that it takes an additional argument so that the default time/iteration can be translated to simulated time/time. I’ve not have problems with this before though!

**Comment by navidcy** [comment]
Haha... I figured it out and deleted my question. But your answer came anyway! :)

**Comment by navidcy** [comment]
> Hm... This might be "type piracy"?
> Yes, I didn’t want to go down the route of implementing the speed estimate properly in ProgressMeter.jl and instead went for the easy way to just locally redefine their function so that it takes an additional argument so that the default time/iteration can be translated to simulated time/time. I’ve not have problems with this before though!

Do we need to explicitly import it perhaps?

```Julia
import ProgressMeter: speedstring
```

before adding the new method?

I don't think it's type piracy because you are defining a method for a type that SpeedyWeather defines, so that's OK!

**Comment by navidcy** [comment]
I think the problem is that we define

```
speedstring(sec_per_iter, dt_in_sec=SpeedyWeather.DT_IN_SEC)
```

which, because we provide a default for `dt_in_sec=SpeedyWeather.DT_IN_SEC` it implies a re-definition of the method `speedstring(::Any)`. That's why it's complaining...

**Comment by milankl** [comment]
I remember having had precompilation warnings for that a long time ago, but not recently. So I don't know why this is coming up now for you.

**Comment by milankl** [comment]
Just ran into this problem again after adding SpeedyWeather.jl the first time with v1.9 It looks like the problem arises from constructors like
```julia
Base.@kwdef AB{NF<:Real}
     a::NF = 1.0
     b::NF = 2.0
end

AB(;kwargs...) = AB{Float64}(;kwargs...)
```
While the 2nd method overwrites `AB()` it also allows `AB(b=2)`, which why I defined it initially. I saw on Julia slack that @charleskawczynski ran into a similar problem. Maybe you have some ideas?

**Comment by navidcy** [comment]
What is `AB(;kwargs...) = AB{Float64}(;kwargs...)` for?

**Comment by milankl** [comment]
Essentially so that one can do `AB(b=2)` (which isn't defined, because `b::Int`, but `a::Float64` in that case) and it would convert `b=2` to `b=2.0`

**Comment by navidcy** [comment]
Btw, the answer to my question was already in your previous post but the coffee hadn't gone to my brain....

**Comment by milankl** [comment]
It would be possible to do
```julia
Base.@kwdef struct ABC{NF<:Real}
      a::NF = convert(NF,1)
      b::NF = convert(NF,2)
end

ABC(;kwargs...) = ABC{Float64}(;kwargs...)
```
because it doesn't define `ABC()` and so the `ABC(;kwargs...)` can be added later

**Comment by charleskawczynski** [comment]
Yeah, `Base.@kwdef` doesn't always provide the constructor that you may want for users-- it's easy if all the types are concrete and separate. Otherwise, I tend to just write my own inner constructor and do diagonalization there. Maybe there's opportunity for a new macro?

**Comment by milankl** [comment]
Can you point me to an example? Cause what I often need is
- a struct `ABC{T}` where all/most fields are of type `T`, so that I can dispatch over it
- default values for the fields directly written into the struct definition
- and a generous constructor that takes any keyword arguments, promotes their type somehow to `T` and creates a `struct{T}`

**Comment by charleskawczynski** [comment]
It sounds like what you're looking for is:

```julia
struct ABC{NF<:Real}
      a::NF
      b::NF
      function ABC{NF}(; a = NF(1), b = NF(2)) where {NF}
            return new{NF}(a, b)
      end
      ABC(; kwargs...) = ABC{promote_type(typeof.((kwargs...,))...)}(;kwargs)
      ABC() = ABC{Float64}()
end
```

It's maybe not the prettiest way to write it, but I think this will do what you want for at least for all float type structs. And of course you can move the inner constructors to outer constructors if you need access to the default constructor

**Comment by milankl** [comment]
With the restructuring of #327 these warnings should disappear, moving this therefore to v0.6

**Comment by milankl** [comment]
In main we're now down to one single precompilation warning
```julia
┌ SpeedyWeather [9e226e20-d153-4fed-8a5b-493def4f21a9]
│  WARNING: Method definition speedstring(Any) in module ProgressMeter at /Users/milan/.julia/packages/ProgressMeter/sN2xr/src/ProgressMeter.jl:683 overwritten in module SpeedyWeather at /Users/milan/.julia/packages/SpeedyWeather/oRCBd/src/output/feedback.jl:201.
│    ** incremental compilation may be fatally broken for this module **
└
```
