### ISSUE TITLE
CI runs on latest Julia release -- should we add more?

### ISSUE THREAD

**Issue by navidcy** [SpeedyWeather/SpeedyWeather.jl#325]
At the moment the CI runs on Julia v1.9
https://github.com/SpeedyWeather/SpeedyWeather.jl/actions/runs/4969025395/jobs/8891967894#step:3:10

Should we add a note in the docs/readme? Should we add a line in the CI.yml to run tests on other versions?

**Comment by milankl** [comment]
I basically didn't want to get hung up on compatibility with older versions of Julia, hence I added the "please use the latest minor release". We could also test on v1.8, but I've been using the `const` declaration in `mutable struct` which isn't available pre 1.8 anyway. You think we should keep testing on older verions too?

**Comment by navidcy** [comment]
No. 1.8 is good. Or only 1.9 is also good. Just note it in the docs or somewhere.

**Comment by milankl** [comment]
adressed with #361
