### ISSUE TITLE
SpectralGrid not defined in v0.5

### ISSUE THREAD

**Issue by madnanabid** [SpeedyWeather/SpeedyWeather.jl#367]
Thanks, it looks warning messages only. When I try to define spectral grid. It says me following.

UndefVarError: `SpectralGrid` not defined

Stacktrace:
 [1] top-level scope
   @ In[7]:1

**Comment by milankl** [comment]
Please install the branch `#main` not the latest release.

**Comment by milankl** [comment]
Did you do `using SpeedyWeather`? `add`ing a package is like `pip install` or `conda install`, `using` is like python's `import`

**Comment by madnanabid** [comment]
thanks, got it, done
