### ISSUE TITLE
16 bit model 

### ISSUE THREAD

**Issue by madnanabid** [SpeedyWeather/SpeedyWeather.jl#375]
┌ Warning: NaR detected at time step 1
└ @ SpeedyWeather ~/.julia/packages/SpeedyWeather/5FE4h/src/output/feedback.jl:150
Weather is speedy: 100%|██████████████████| Time: 0:00:00 ( 7.76 millenia/day)

**Comment by milankl** [comment]
duplicate of #137 closing here in favour for other issue
