### ISSUE TITLE
Initial conditions from PDEArena

### ISSUE THREAD

**Issue by milankl** [SpeedyWeather/SpeedyWeather.jl#377]
From https://github.com/microsoft/pdearena/blob/main/pdedatagen/shallowwater/datagen.jl I conclude that https://arxiv.org/abs/2302.06594 used the `:random2` initial conditions as coded up here

https://github.com/microsoft/pdearena/blob/f50e1ebed6248c92383ea2358ecb97e9b5e175dd/pdedatagen/shallowwater/modified_init.jl#L63-L101

The same initial conditions can be used with v0.6 as follows (you can write this down in your REPL or copy it into a notebook top to bottom)

```julia
using SpeedyWeather
```

Now we define the parameters they use too
```julia
Base.@kwdef struct PDEArenaRandom2 <: SpeedyWeather.InitialConditions
    
    # zonal wind
    offset::Float64 = rand(80:120)
    coeff1::Float64 = rand(-20:30)
    coeff2::Float64 = rand(-20:40)
    coeff3::Float64 = rand(-20:40)

    # perturbation
    A::Float64 = 1e-4
    m::Float64 = 6
    θ0::Float64 = 45
    θw::Float64 = 10
end
```
it's packed into a `struct` with default values as we'll use multiple dispatch to define a new "class" (in python language) of initial conditions. The actual function we need to define for `PDEArenaRandom2` is `initial_conditions!(::PrognosticVariables,::PDEArenaRandom2,::ModelSetup)` which will be called at model initialisation, so

```julia
function SpeedyWeather.initial_conditions!(   progn::PrognosticVariables{NF},
                                              initial_conditions::PDEArenaRandom2,
                                              model::SpeedyWeather.ModelSetup) where NF
        
    # unpack and rename
    (;Grid, nlat_half) = model.spectral_grid
    (;latd, londs, coslat, sinlat, radius) = model.geometry
    (;offset, coeff1, coeff2, coeff3) = initial_conditions

    # zonal wind
    u_grid = zeros(Grid{NF},nlat_half)
    for (j,ring) in enumerate(RingGrids.eachring(u_grid))
        u = coeff1 * rand(NF) * coslat[j] -
            coeff2 * coslat[j]^2 +
            coeff3 * sinlat[j] * coslat[j] +
            offset
        for ij in ring
            u_grid[ij] = u
        end
    end

    # transform to spectral and take the curl for vorticity initial conditions
    u = spectral(u_grid,model.spectral_transform)
    v = zero(u)
    (;vor) = progn.layers[1].timesteps[1]
    SpeedyTransforms.curl!(vor,u,v,model.spectral_transform)
    vor ./= radius       # curl omits /radius scaling, do now

    # zonal wave perturbation
    (;A, m, θ0, θw) = initial_conditions

    vor_grid = zeros(Grid{NF},nlat_half)
    for (j,ring) in enumerate(RingGrids.eachring(vor_grid))
        a = coslat[j] * exp(-((latd[j] - θ0)/θw)^2)     # lat-dependent component
        for ij in ring
            b = A/2*cosd(m*londs[ij])                   # lon-dependent component
            vor_grid[ij] = a*b
        end
    end

    # add zonal wave perturbation
    vor_perturbation = spectral(vor_grid,model.spectral_transform)
    vor .+= vor_perturbation

    # make less symmetric
    vor[15,1:14] .+= 5e-6*randn(14)

    return nothing
end
```
So we've extended the `initial_conditions!` functions from SpeedyWeather for our new initial conditions. I've just copied their code over and adapted to some of the new structure since v0.2.1 and also use the more general `for (j,ring) in enumerate(eachring(::AbstractGrid))` and `for ij in ring` logic  (see #132) as this works for all grids not just full grids. With this defined you can now do
```julia
spectral_grid = SpectralGrid(trunc=85,nlev=1,Grid=FullClenshawGrid)
initial_conditions = PDEArenaRandom2()
model = ShallowWaterModel(;spectral_grid,initial_conditions)
simulation = initialize!(model)    # this actually calls initial_conditions! from above
```
Before you even run the simulation you can have a look at the prognostic variables, which by default shows you the current state of the surface vorticity, which are the initial conditions `PDEArenaRandom2` sets anyway

![image](https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/ca36c6df-472d-4381-a8d2-8a79c941f469)

I hope I didn't mess up something while copying it in here, but one of the major selling points of SpeedyWeather is supposed to be that you can extend the model externally, meaning without creating a branch or hardcoding something new in. One is supposed to interactively define new components, like initial conditions shown here. More tomorrow.

@ningliu-iga

**Comment by milankl** [comment]
Also just realised that their initial conditions are actually my initial conditions from v0.2.1 while I was playing around with the model -- just a bite more randomised.

https://github.com/SpeedyWeather/SpeedyWeather.jl/blob/1881d47ab3f28a85e433ccaaf5fc7218e4792b8d/src/prognostic_variables.jl#L20C5-L52

**Comment by milankl** [comment]
To illustrate what these initial conditions were (you can see all the waves bouncing around)

https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/a8746923-a37e-481c-b630-73b2a1dd1677

**Comment by milankl** [comment]
@ningliu-iga I have a suggestion, which is pysically a much clearer defined problem. Instead of setting the initial conditions for vorticity, we set the initial conditions for the interface displacement eta, that's pressure in the shallow water system -- but u,v,vor,div are zero initially. Physically that corresponds to throwing a lot of pebbles into a pond or waves in a pool and seeing how the waves propagate and interfere

https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/b1d9c693-d43d-4edf-b6cb-dea6d0aa36a8

compare to (stolen from pinterest)

![image](https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/f26a7d03-e664-41c6-9368-016bcc865838)


but in our case in the atmosphere and on the sphere, and the waves interact with the orography too (you can spot the himalayas in the video). That way we are honest that we are essentially designing a linear problem, although the equations that are solved are non-linear.

**Comment by milankl** [comment]
Motivated by the pool image I think I already found our colourmap 🥳 


https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/95aa92e0-5887-4895-8b0b-fd266b72e590

and divergence where the orography is a bit more pronounced


https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/b8ded930-8452-43a5-8242-d8513bbf121c

**Comment by milankl** [comment]
The initial conditions are just this
```julia
Base.@kwdef struct RandomWaves <: InitialConditions  
    # random interface displacement field
    A::Float64 = 2000       # amplitude [m]
    lmin::Int64 = 10        # minimum wavenumber
    lmax::Int64 = 20        # maximum wavenumber
end

function initial_conditions!(   progn::PrognosticVariables{NF},
                                initial_conditions::RandomWaves,
                                model::ShallowWater) where NF
        
    (;A, lmin, lmax, power) = initial_conditions
    (;trunc) = progn

    η = progn.surface.timesteps[1].pres
    η .= randn(LowerTriangularMatrix{Complex{NF}},trunc+2,trunc+1)

    # zero out other wavenumbers
    η[1:min(lmin,trunc+2),:] .= 0
    η[min(lmax,trunc+2):trunc+2,:] .= 0

    # scale to amplitude
    η_grid = gridded(η,model.spectral_transform)
    η_min,η_max = extrema(η_grid)
    η .*= (A/max(abs(η_min),abs(η_max)))

    return nothing
end
```

The last videos where at T255, which takes about 1min on 1core for 48 hours. PDEArena used T62 (for whatever reason not T63) which would be much faster, I run the simulations like so

```julia
spectral_grid = SpectralGrid(trunc=255,nlev=1)
implicit = SpeedyWeather.ImplicitShallowWater(spectral_grid,α=0.5)
output = OutputWriter(spectral_grid,ShallowWater,output_dt=0.5,output_vars=[:u,:vor,:div,:pres])
orography = EarthOrography(spectral_grid,smoothing_truncation=255)
model = ShallowWaterModel(;spectral_grid,orography,output,initial_conditions,implicit);
simulation = initialize!(model);
run!(simulation,output=true,n_days=2)
```

**Comment by rejuvyesh** [comment]
Apologies for being SpeedyWeather noobs but this is super useful for future datasets! Will update PDEArena datagen too!

**Comment by milankl** [comment]
@rejuvyesh you want me to open a pull request with these new initial conditions and the update to SpeedyWeather.jl v0.6? Otherwise @ me in?

**Comment by milankl** [comment]
@rejuvyesh does PDEArena still use the outdated v0.2.1? Let me know if you need help to define a new setup compatible with newer versions, otherwise I'll close this issue.
