### ISSUE TITLE
low precision stochastic rounding

### ISSUE THREAD

**Issue by madnanabid** [SpeedyWeather/SpeedyWeather.jl#411]
grid=randn(FullGaussianGrid{BFloat16sr},16)
spec = spectral(grid);
grid2 = gridded(spec);
spec2 = spectral(grid2);
grid3 = gridded(spec2);

plot(grid3)
ERROR: MethodError: no method matching trunc(::Type{Int64}, ::BFloat16sr)

Closest candidates are:
  trunc(::Type{T}, ::Missing) where T
   @ Base missing.jl:154
  trunc(::Type{T}, ::Rational) where T
   @ Base rational.jl:471
  trunc(::Type{T}, ::BigFloat) where T<:Union{Signed, Unsigned}
   @ Base mpfr.jl:327

**Comment by milankl** [comment]
Sorry, this is an error for StochasticRounding.jl, this has nothing to do with SpeedyWeather.jl.

You can fix it locally though simply by defining it
```julia
Base.trunc(::Type{T},x::BFloat16sr) where {T<:Integer} = trunc(T,BFloat16(x))
```

**Comment by milankl** [comment]
Also we already have that issue open https://github.com/milankl/StochasticRounding.jl/issues/72
