### ISSUE TITLE
Convection too weak?!

### ISSUE THREAD

**Issue by milankl** [SpeedyWeather/SpeedyWeather.jl#436]
I believe that there's currently some bug in the convection algorithm making the convection too weak and removing too little humidity / over too long a time frame, see video at T42 covering 100 days. Excess humidity is removed over O(months) insted of order (days) and the mm/hr are about a factor of 10-20x too low

https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/76eebea7-bac5-422c-87c6-7c254980deab

@white-alistair

**Comment by white-alistair** [comment]
Hmm. Have you got a sense for whether this is likely due to convection not always being diagnosed when it should be, or the convection itself being too weak, or the convective precipitation being too weak?

**Comment by milankl** [comment]
Well convective precipitation only occurs when convection is diagnosed. Given it's raining in some tropical regions for 50 days non-stop, I don't think the diagnosis is the primary problem. I reckon it's the convection itself being too weak, or removing too little humidity hence it keeps on convecting and therefore precipitating. It's okay to start with convection everywhere in the tropics for the first days but it takes too long to reach the typical patchiness of convection in the real atmosphere, and mm/hr values should be higher, comparison:

![image](https://github.com/SpeedyWeather/SpeedyWeather.jl/assets/25530332/d064fd0a-c75d-4197-a9b6-56a50146aa8d)

So I'm expecting O(1mm/hr) as typical precipitation rate in convective cells in the tropics, currently it's not as patchy as it should be (note the satellite picture is half-hourly whereas the video frames have accumulated rainfall over 6 hours) and not as strong as it should be.

**Comment by milankl** [comment]
Maybe worth to follow [Frierson, 2007](https://doi.org/10.1175/JAS3935.1) as this idealised convection scheme seems to be fairly similar to what we currently do, but might be better documented / is more modern than what we currently have.

**Comment by milankl** [comment]
#442 uses `time_scale = Minute(10)` which makes a stronger convection and gives a similar strength of convection in comparision to large scale precip
