### ISSUE TITLE
Question about example in Docs/SpeedyTransforms/Geostrophy

### ISSUE THREAD

**Issue by navidcy** [SpeedyWeather/SpeedyWeather.jl#452]
At

https://speedyweather.github.io/SpeedyWeather.jl/dev/speedytransforms/#Example:-Geostrophy

the `u_grid` and `v_grid` in

```Julia
RingGrids.scale_coslat⁻¹!(u_grid)
RingGrids.scale_coslat⁻¹!(v_grid)
```

are never defined, right?

**Comment by milankl** [comment]
It's u,v in the line above, I seem to just have renamed it without consistency ... 🙈

**Comment by navidcy** [comment]
I'll fix it ;)
