### ISSUE TITLE
Replace `PythonPlot` with a Julia-based plotting library in Docs

### ISSUE THREAD

**Issue by navidcy** [SpeedyWeather/SpeedyWeather.jl#482]
E.g. CairoMakie

**Comment by milankl** [comment]
Yes, absolutely. My problem is just that I'm still more used to matplotlib + cartopy than to Makie, but I should change that. If you want to add `GeoMakie, GLMakie` to `docs/Project.toml` go ahead, then we can replace the examples one by one.

**Comment by milankl** [comment]
All Makie now
