### ISSUE TITLE
spectral_grid sample of usage: should it say 'nlev', not 'nlayers'?

### ISSUE THREAD

**Issue by dankelley** [SpeedyWeather/SpeedyWeather.jl#581]
First, I came to SpeedyWeather via the JOSS podcast, and then I read the JOSS paper.  I'm very excited to start trying this, as someone old enough to remember those punch-cards in the old Fortran.  (I first used Fortran before f77 came out ... that's a way back!)

In looking at https://speedyweather.github.io/SpeedyWeather.jl/dev/how_to_run_speedy/ I saw the suggested line
```julia
spectral_grid = SpectralGrid(nlayers=1)
```
but when I tried that (with SW as of now, and Julia as of a few days ago) I got an error. However, when I looked at the docs, I discovered that maybe the new version should say `nlev` instead of `nlayers`.

I didn't make a PR request because I'm not too sure, and when I grep I find a lot of instances of the `nlayers` style:
```
$ git grep 'nlayers=1'|wc
      28     147    2159
```

**Comment by milankl** [comment]
Hi Dan! No this is no bug, you've just mixed up the docs version with the SpeedyWeather version installed. Until v0.10 included we call it `nlev` now on main it's renamed to `nlayers` for clarity and consistency. So if you look into the dev docs you'll see `nlayers` which does correspond to the main branch! You can switch in the docs to v0.10 though and you'll find it documented as it was before!

**Comment by dankelley** [comment]
Excellent -- thanks so much.  I'm excited to try more of this over the weekend.
