### ISSUE TITLE
Profiling of timestep

### ISSUE THREAD

**Issue by treigerm** [SpeedyWeather/SpeedyWeather.jl#594]
As requested by @milankl, here's a dump of the profiling I did of the `run!` function.  All of the profiling was done on the current main branch (210bd22e7b04c41cb647fdf8c5b046cff6074ac6).

Running
```julia
using SpeedyWeather, Profile, PProf
spectral_grid = SpectralGrid(trunc=31, nlayers=8)          
orography = EarthOrography(spectral_grid)              
model = PrimitiveWetModel(; spectral_grid, orography)   
simulation = initialize!(model)                        
run!(simulation, period=Day(10))
Profile.clear()
@profile run!(simulation, period=Day(10))
pprof()
```
produces 
![Screenshot 2024-10-23 at 08 28 59](https://github.com/user-attachments/assets/1d84b041-3bd4-4e65-87b0-0bcc2d329873)

Turning off the physics with 
```julia
using SpeedyWeather, Profile, PProf
spectral_grid = SpectralGrid(trunc=31, nlayers=8)          
orography = EarthOrography(spectral_grid)              
model = PrimitiveWetModel(; spectral_grid, orography, physics=false)   
simulation = initialize!(model)                        
run!(simulation, period=Day(10))
Profile.clear()
@profile run!(simulation, period=Day(10))
pprof()
```
produces
![Screenshot 2024-10-23 at 09 27 19](https://github.com/user-attachments/assets/19e342e3-7247-476d-bed8-9686e9928703)

I ran the experiments with:
- Julia 1.10.4
- Apple M3 Max with 36GB memory
- macOS Sonoma 14.4

**Comment by milankl** [comment]
Awesome!! Convection is expensive ouch!! So is `physics = false` about 2x faster? Overall this is good news because parallelising the parameterisations is easy from an algorithmic point of view and hopefully also maps nicely onto the GPU threads. This also motivates me to try the octahedral Gaussian grid starting with 4 instead of 20 points. In the limit of high resolution this doesn't make a difference but at T31 it might shave off some 10-20% because of fewer grid points (will update with exact numbers) And the reason for why ECMWF picked 20 is one old paper that says so I believe @hottad ?

**Comment by treigerm** [comment]
Yes, with `physics = false` I get around `(2.63 millenia/day)`, whereas with `physics = true` I get around `(1300 years / day)`. However, these measurements are taken with other stuff running on my laptop in my background so the exact numbers might vary a bit. But overall 2x faster seems like the right order of magnitude!

**Comment by hottad** [comment]
Hi Milan and Tim,
> And the reason for why ECMWF picked 20 is one old paper that says so I believe @hottad ?
Yes, the rationale is that to ensure exact (upto ~ machine-precision) grid-to-wave transform, we need to start from 20 nearest to the poles. Now that we know that inexact transforms (like on HEALPix and OctaHEALPix) work just fine, the reason to start with 20 is rather vague.

**Comment by milankl** [comment]
Redoing the profiling on my intel macbook with the `OctaminimalGaussianGrid`

```julia
using SpeedyWeather, Profile, PProf
spectral_grid = SpectralGrid(trunc=31, nlayers=8, Grid=OctaminimalGaussianGrid)          
model = PrimitiveWetModel(spectral_grid)   
simulation = initialize!(model)                        
run!(simulation, period=Day(10))
Profile.clear()
@profile run!(simulation, period=Day(10))
pprof()
```

![image](https://github.com/user-attachments/assets/91ea5a78-e753-4450-860f-ba8abdaafb53)

Some numbers

- physics 36% (12% convection, 5% large-scale condensation, 5% get column, vertical diffusion 3%)
- dynamics 32% (temperature 9%, humidity 8%, vordiv 6%, bernoulli 3%)
- horizontal diffusion 2%
- implicit 6%
- time stepping 1%
- transform spec to grid (at the end of a time step) 17%
