### ISSUE TITLE
How to use SpeedyWeather to diagnose model run instability caused by initial conditions.

### ISSUE THREAD

**Issue by rocroc2017** [SpeedyWeather/SpeedyWeather.jl#643]
Dear Dr. Klöwer
     I plot the simulation.prognostic_variables(temp,humid,pres,vor and div) in layer8
temp in day 0 and day 6
![t0](https://github.com/user-attachments/assets/4be953ff-c962-4939-bcf3-88e2d4e2051b)
![t6](https://github.com/user-attachments/assets/d91eed61-d74e-4316-bbb1-8de754322bbf)
humid in day 0 and day 6
![humid0](https://github.com/user-attachments/assets/b85b3f0f-86b3-489c-aa0a-c9a21031379d)
![humid6](https://github.com/user-attachments/assets/7b7aff41-a885-4ae3-a04e-8b6e98a3b532)
pres in day 0 and day6 
![pres0](https://github.com/user-attachments/assets/e66041fb-1e0b-4c70-8c64-754d43783520)
![pres6](https://github.com/user-attachments/assets/f30bb854-6e2b-49ec-8bfc-2f390f8e9ed3)
vor in day 0 and day6
![vor0](https://github.com/user-attachments/assets/ebe4ebc3-b3cc-429c-93f5-5cee4192ca95)
![vor6](https://github.com/user-attachments/assets/2496c542-dbbb-41d8-8ea7-250a08c02a0f)
div in day 0 and day6
![div0](https://github.com/user-attachments/assets/ee98432f-008f-41df-8c0b-dfe5294b10bd)
![div6](https://github.com/user-attachments/assets/cb3222ea-395b-4636-bfec-d5ef159f794c)

I find there are small changes in temp, humid and pres, but there are large changes in vor and div.
However, I am unsure of the next steps to take in order to identify the issue and ensure the model can run stably for long-term integration. Could you please provide some suggestions? Thank you very much.

**Comment by milankl** [comment]
Closed in favour of #630
