### ISSUE TITLE
test with posits

### ISSUE THREAD

**Issue by oscardssmith** [SpeedyWeather/SpeedyWeather.jl#77]
the performance would be awful (cause emulated floating point), but it would be interesting to use https://github.com/milankl/SoftPosit.jl to test posit accuracy at 16 bit.

**Comment by milankl** [comment]
Posit arithmetic is actually emulated using (un)signed integers. So on every operation a 16-bit posit is disassembled into its different bits (sign, regime, exp and fraction) and then afterwards they are concatenated again. But its slow, yes 😄 

For SpeedyWeather.jl to run in 16-bit posits there are currently two bottlenecks
- a type-flexible fourier transform (everything else is type flexible at the moment), see #31 
- (a much bigger bottleneck) rewriting the precision-critical algorithms for low precision. At the moment everything works fine in Float32, but lower precision will likely fail. So tricks like scaling, reordering, compensation have to be further build in.

**Comment by milankl** [comment]
See also https://github.com/milankl/SoftPosit.jl/issues/64

**Comment by milankl** [comment]
closed for the favour of #137
